version: '2'
services: 
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: aclsnat_c5user
      MYSQL_PASSWORD: 3c]zrdSBDOea
      MYSQL_DATABASE: aclsnat_c5
    volumes_from:
     - data
    expose:
      - "3306"
  web:
    image: chriswayg/concrete5.7
    restart: always
    ports: 
     - "80:80"
    links:
     - db
    volumes_from:
     - data
  data:
    image: busybox
    volumes:
     - ./db-script/:/docker-entrypoint-initdb.d
     - ./src/:/var/www/html/application/
    command: tail -f /dev/null
