<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-11-27T22:43:34+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      debug.display_errors
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Concrete5 Defined Website Name',
    'version_installed' => '5.7.5.8',
    'misc' => array(
        'access_entity_updated' => 1479053396,
        'latest_version' => '5.7.5.9',
        'do_page_reindex_check' => false,
        'favicon_fid' => '3',
        'iphone_home_screen_thumbnail_fid' => '4',
        'modern_tile_thumbnail_fid' => '5',
        'modern_tile_thumbnail_bgcolor' => '',
    ),
    'seo' => array(
        'canonical_url' => 'http://localhost',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
);
